const $=s=>document.querySelector(s);const state={sources:[],feeds:[],selected:null};
const token=()=>sessionStorage.getItem('sidefeed-token')||'';
async function api(path,options={}){const headers=new Headers(options.headers||{});if(token())headers.set('authorization',`Bearer ${token()}`);if(options.body&&!headers.has('content-type'))headers.set('content-type','application/json');const response=await fetch(path,{...options,headers});if(!response.ok){let message=`${response.status} ${response.statusText}`;try{message=(await response.json()).error||message}catch{}throw new Error(message)}if(response.status===204)return null;return response.json()}
function notice(message,error=false){const node=$('#notice');node.textContent=message;node.className=error?'error':'';if(message)setTimeout(()=>{if(node.textContent===message)node.textContent=''},4500)}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function refresh(){try{const health=await api('/healthz');$('#status').textContent=`v${health.version} online`;$('#status').className='pill ok';[state.sources,state.feeds]=await Promise.all([api('/api/v1/sources'),api('/api/v1/feeds')]);render()}catch(error){$('#status').textContent='Needs attention';$('#status').className='pill bad';notice(error.message,true)}}
function render(){
  $('#source-count').textContent=state.sources.length;$('#feed-count').textContent=state.feeds.length;
  $('#sources').className=`stack${state.sources.length?'':' empty'}`;$('#sources').innerHTML=state.sources.map(s=>`<div class="card"><h3>${escapeHtml(s.title||s.kind.toUpperCase())}</h3><p>${escapeHtml(s.url)}</p><div class="card-actions"><button class="secondary poll" data-id="${s.id}">Poll now</button></div></div>`).join('')||'No sources yet.';
  $('#feeds').className=`stack${state.feeds.length?'':' empty'}`;$('#feeds').innerHTML=state.feeds.map(f=>`<button class="secondary feed" data-slug="${escapeHtml(f.slug)}"><strong>${escapeHtml(f.title)}</strong> · ${f.public?'public':'private'}</button>`).join('')||'No feeds yet.';
  const feedSelect=$('#attach-form select[name=feed]'),sourceSelect=$('#attach-form select[name=source]');feedSelect.innerHTML='<option value="">Choose feed</option>'+state.feeds.map(f=>`<option value="${f.slug}">${escapeHtml(f.title)}</option>`).join('');sourceSelect.innerHTML='<option value="">Choose source</option>'+state.sources.map(s=>`<option value="${s.id}">${escapeHtml(s.title||s.url)}</option>`).join('');
  document.querySelectorAll('.poll').forEach(b=>b.onclick=()=>poll(b.dataset.id));document.querySelectorAll('.feed').forEach(b=>b.onclick=()=>loadFeed(b.dataset.slug));
}
async function loadFeed(slug){try{const page=await api(`/api/v1/feeds/${encodeURIComponent(slug)}/items?limit=30`);state.selected=slug;const feed=state.feeds.find(f=>f.slug===slug);$('#timeline-title').textContent=feed?.title||slug;$('#feed-links').innerHTML=`<div class="links"><a href="/feeds/${slug}.rss">RSS</a><a href="/feeds/${slug}.json">JSON</a><a href="/feeds/${slug}/newsletter">Newsletter</a></div>`;$('#items').className=`stack${page.items.length?'':' empty'}`;$('#items').innerHTML=page.items.map(i=>`<article class="card"><time>${new Date(i.published_at).toLocaleString()}</time><h3><a href="${escapeHtml(i.url||'#')}" rel="noreferrer">${escapeHtml(i.title||'Untitled')}</a></h3><p>${escapeHtml(i.summary||i.content||'')}</p></article>`).join('')||'No items yet. Poll a connected source.'}catch(error){notice(error.message,true)}}
async function poll(id){try{const result=await api(`/api/v1/sources/${id}/poll`,{method:'POST'});notice(`Imported ${result.imported} items.`);if(state.selected)loadFeed(state.selected)}catch(error){notice(error.message,true)}}
$('#save-token').onclick=()=>{sessionStorage.setItem('sidefeed-token',$('#token').value);notice('Token saved for this session.');refresh()};$('#token').value=token();
$('#source-form').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));if(!data.title)delete data.title;try{await api('/api/v1/sources',{method:'POST',body:JSON.stringify(data)});event.target.reset();notice('Source added.');refresh()}catch(error){notice(error.message,true)}};
$('#feed-form').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target),data={slug:form.get('slug'),title:form.get('title'),public:form.get('public')==='on'};try{await api('/api/v1/feeds',{method:'POST',body:JSON.stringify(data)});event.target.reset();notice('Feed created.');refresh()}catch(error){notice(error.message,true)}};
$('#attach-form').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));try{await api(`/api/v1/feeds/${encodeURIComponent(data.feed)}/sources/${encodeURIComponent(data.source)}`,{method:'POST'});notice('Source connected to feed.');loadFeed(data.feed)}catch(error){notice(error.message,true)}};
refresh();
